import React, { Component, Fragment } from 'react';
import { Segment } from 'semantic-ui-react';

export default class JuanSide extends React.Component {
    render(){
        return(
            <div>
                <Segment>
                    first
                </Segment>
                <Segment>
                    second
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    text
                </Segment>
                <Segment>
                    last2
                </Segment>
                <Segment>
                    last
                </Segment>
            </div>
        )
    }
}